server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:file:./meetings.db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  assemblyai:
    api-key: ${ASSEMBLYAI_API_KEY:your_assemblyai_key_here}
    base-url: https://api.assemblyai.com/v2
  gemini:
    api-key: ${GEMINI_API_KEY:your_gemini_key_here}
    base-url: https://generativelanguage.googleapis.com/v1beta
    model: gemini-pro

logging:
  level:
    com.meetingsummarizer: DEBUG